config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'

  get 'static_pages/help'

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'about' => 'static_pages#about'

  get 'help' => 'static_pages#help'
  get 'contact' => 'static_pages#contact'

  root                 'static_pages#home'

  get   'login' => 'sessions#new'
  post   'login' =>'sessions#create'
  delete  'logout' =>'sessions#destroy'

  get 'signup' => 'users#new'
  resources :users
  post 'projects/:id' =>'projects#add_developer'
  post 'projects/:project_id/stories/:id'=>'stories#replace_user'
  get 'projects/:project_id/stories/:id/signoff'=>'stories#signoff', as: :signoff
  post 'projects/:project_id/search'=>'projects#search', as: :search

  resources :projects do
    resources :stories
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :story
  before_save{self.email=email.downcase}
  validates :name, presence: true
  validates :email, presence: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index,:edit,:update,:show,:destroy]
  before_action :correct_user, only: [:edit,:update]

  def index
    @users=User.all
  end

  def new
    @user=User.new
  end

  def create
    @test =0
    User.all.each do |u|
      if u.email == params[:user][:email]
        @test =1
      end
    end
    if @test ==0
      @user=User.new(user_params)
      @user.admin=true  if params[:admin]=="true"
      if @user.save
        #UserMailer.welcome(@user).deliver
        flash[:success]="Successful created!"
        redirect_to users_path
      else
        render 'new'
      end
    else
      @user= User.new
      flash[:danger]="this email already registered!"
      render 'new'
    end
  end

  def show
    @user=User.find(params[:id])
  end

  def edit
    @user=User.find(params[:id])
  end

  def update
    @user=User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success]="Profile updated!"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success]="User deleted"
    redirect_to users_url
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :admin)
  end

  def logged_in_user
    unless logged_in?
      flash[:danger]="Pleasee log in."
      redirect_to login_path
    end
  end

  def correct_user
    @user=User.find(params[:id])
    redirect_to(current_user) unless current_user?(@user)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.erb
<p>
  <strong>name</strong>
  <%= user.name %>
</p>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<% if current_user.admin? %>
 <p><b><u><%= link_to "New User", signup_path %></u></b></p>
<table border="2">
  <tr>
    <td width="100" align="center">Name:</td>
    <td width="100" align="center">Role:</td>
    <td width="100" align="center">Operation:</td>
  </tr>
  <% @users.each do |user| %>
    <tr>
      <td align="center">
        <b><%= link_to user.name, user %></b>
      </td>
      <td align="center">
        <%if user.admin?%>
            Admin
        <% else %>
            Developer
        <% end %>
      </td>
      <td align="center">
        <%if !current_user?(user)%>
            <b><%= link_to "delete", user, method: :delete,data: {confirm: "You sure?"}%></b>
        <%end%>
      </td>
    </tr>
  <% end %>
</table>
    <br>
   
<% else %>
    <table border="2">
      <tr>
        <td width="100" align="center">Name:</td>
        <td width="100" align="center">Admin:</td>
      </tr>
      <% @users.each do |user| %>
          <tr>
            <td align="center">
              <b><%= link_to user.name, user %></b>
            </td>
            <td align="center">
              <%if user.admin?%>
                  Yes
              <% else %>
                  No
              <% end %>
            </td>
          </tr>
      <% end %>
    </table>
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>
      
      <%= radio_button_tag(:admin, false) %>
      <%= label_tag(:role_developer, "Developer") %>
      <%= radio_button_tag(:admin, true) %>
      <%= label_tag(:role_admin, "Admin") %>
     <br>

      <%= f.submit "Create account",class: "btn btn-primary"  %>
    <% end %>

app/views/users/show.html.erb
<% provide(:title, 'Profile') %>
<h1>User Profile</h1>
<table border="2">
  <tr>
    <td width="100" align="center">Name:</td>
    <td width="100" align="center">Email:</td>
    <td width="100" align="center">Role:</td>
  </tr>
  <tr>
    <td align="center"><%= @user.name %></td>
    <td align="center"><%= @user.email %></td>
    <td align="center">
      <% if@user.admin %>
          Administer
      <%else%>
          Developer
      <%end%>
    </td>
  </tr>
</table>

<p>---------------------------------------------------</p>
<p><b>Created Stories:</b></p>
<% if Story.find_by( createdby: current_user.id)!=nil%>
    <table border="2">
      <tr>
        <td width="100" align="center">Project_Title:</td>
        <td width="100" align="center">Title</td>
        <td width="100" align="center">Description</td>
        <td width="100" align="center">Point</td>
        <td width="100" align="center">Stage</td>
        <td width="100" align="center">Developer1</td>
        <td width="100" align="center">Developer2</td>
      </tr>
    <% Story.where(:createdby => current_user.id).each do |s|%>
       <tr>
         <td align="center"><%=s.project.title%></td>
         <td align="center"><%=s.title%></td>
        <td align="center"><%=s.description%></td>
        <td align="center"><%=s.point%></td>
        <td align="center"><%=s.stage%></td>
        <td align="center">
          <% if s.users[0] %>
            <%= s.users[0].name%>
          <% end %>
        </td>
        <td align="center">
          <% if s.users[1] %>
            <%= s.users[1].name%>
          <% end %>
        </td>

    <%end%>
    </table>
<% else %>
    This user haven't created any story !
<%end%>
<p>---------------------------------------------------</p>

<p><b>Signed Stories:</b></p>
<% if current_user.story_id!=nil%>
    <table border="2">
      <tr>
        <td width="100" align="center">Project_Title:</td>
        <td width="100" align="center">Title</td>
        <td width="100" align="center">Description</td>
        <td width="100" align="center">Point</td>
        <td width="100" align="center">Stage</td>
        <td width="100" align="center">Developer1</td>
        <td width="100" align="center">Developer2</td>
      </tr>
      <tr>
            <td align="center"><%=Project.find(current_user.project_id).title%></td>
            <td align="center"><%=Story.find(current_user.story_id).title%></td>
            <td align="center"><%=Story.find(current_user.story_id).description%></td>
            <td align="center"><%=Story.find(current_user.story_id).point%></td>
            <td align="center"><%=Story.find(current_user.story_id).stage%></td>
            <td align="center">
              <% if Story.find(current_user.story_id).users[0] %>
                  <%= Story.find(current_user.story_id).users[0].name%>
              <% end %>
            </td>
            <td align="center">
              <% if Story.find(current_user.story_id).users[1] %>
                  <%= Story.find(current_user.story_id).users[1].name%>
              <% end %>
            </td>
      </tr>
    </table>
<% else %>
    This user haven't signed up any story !
<%end%>

<p>---------------------------------------------------</p>

<b><u><%= link_to "show all projects", projects_path %></u></b>
<% if current_user.admin? && current_user?(@user)%>
    <br><br>
    <b><u><%= link_to "New User", signup_path %></u></b>
<%end%>