config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'

  get 'static_pages/help'

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'about' => 'static_pages#about'

  get 'help' => 'static_pages#help'
  get 'contact' => 'static_pages#contact'

  root                 'static_pages#home'

  get   'login' => 'sessions#new'
  post   'login' =>'sessions#create'
  delete  'logout' =>'sessions#destroy'

  get 'signup' => 'users#new'
  resources :users
  post 'projects/:id' =>'projects#add_developer'
  post 'projects/:project_id/stories/:id'=>'stories#replace_user'
  get 'projects/:project_id/stories/:id/signoff'=>'stories#signoff', as: :signoff
  post 'projects/:project_id/search'=>'projects#search', as: :search

  resources :projects do
    resources :stories
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :stories, dependent: :destroy
  has_many :users
  validates :title, presence: true
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :logged_in_user, only: [:create,:new, :index,:edit,:update,:show,:destroy]
  #before_action :correct_user, only: [:edit,:update]
  def new
    @project = Project.new
    @developers=aviable_developers
   
  end
  
  def create
    @project = Project.new(project_params)
    
    if @project.save
      @project.users.each do |u|
        u.project_id = nil
        u.story_id = nil
      end
      params[:developer_ids].each do |developer_id|
      @user=User.find(developer_id)
      @user.project_id=@project.id
      @user.save
    end
      redirect_to @project
    else
      render 'new'
    end
  end

  def search
    @project = Project.find(params[:project_id])
    @test = 0
    @stories = nil
    if params[:story][:title].length!=0 or params[:story][:description].length!=0
      if params[:story][:description].length==0
        @stories = Story.where("title like :k",:k=>"%#{params[:story][:title]}%")
      elsif params[:story][:title].length==0
        @stories = Story.where("description like :k",:k=>"%#{params[:story][:description]}%")
      else
        @stories = Story.where("title like :k or description like :w",:k=>"%#{params[:story][:title]}%", :w=>"%#{params[:story][:description]}%")
      end
      if @stories == nil
        flash.now[:danger]='can not find the specific story in this project!'
      end
      @stories.each do |s|
        if s.project_id == @project.id
          @test =1
        end
      end
      if @test == 0
          flash.now[:danger]='can not find the specific story in this project!'
      end
    else
      flash.now[:danger]='please input title and/or description !'
    end
  end



  def update
    @project = Project.find(params[:id])
    @users=@project.users
    if @users
      @users.each do |user|
        user.project_id=nil
        user.story_id = nil
        user.save
      end
    end
    @ids = params[:developer_ids]
    if @ids
      @ids.each do |developer_id|
        @user=User.find(developer_id)
        @user.project_id=@project.id
        @user.save
      end
    end
    @project.update(project_params)
    redirect_to projects_path
  end

  def add_developer
    @user1 = User.new()
    @project = Project.find(params[:id])
    @user1 = User.find_by(user_params)

    if @user1!=nil && @user1.project_id == nil && !@user1.admin?
      @user1.project_id = @project.id
      @user1.save
      redirect_to @project
    elsif @user1==nil
      flash.now[:danger]='this user does not exists!'
    elsif @user1.project_id !=nil
      if @user1.project_id == @project.id
        flash.now[:danger]='this user already belongs to this project!'
      else
        flash.now[:danger]='this user already belongs to other project!'
      end
    elsif @user1.admin?
      flash.now[:danger]='you cannot add an admin to a project!'
    end
  end

  def show
    @user = User.new()
    @project = Project.find(params[:id])
    @point1 = 0
    @point2= 0
    @point3 = 0
    @point4 =0
    @point5 =  0
    @project.stories.each do |s|
      if s.stage == 'Analysis'
        @point1 += s.point.to_f
      elsif s.stage == 'Read For Dev'
        @point2 += s.point.to_f
      elsif s.stage == 'In Dev'
        @point3 += s.point.to_f
      elsif s.stage == 'Dev Complete'
        @point4 += s.point.to_f
      elsif s.stage == 'In Test'
        @point5 += s.point.to_f
      end
    end
  end

  def edit
    @project = Project.find(params[:id])
    @chosen_dev=@project.users
    @developers=aviable_developers
  end


  def index
    @projects = Project.all
  end

  def destroy
    @project = Project.find(params[:id])
    @project.users.each do |u_p|
      u_p.project_id = u_p.story_id=  nil
      u_p.save
    end
    @project.stories.each do|s|
      s.destroy
    end
    @project.destroy
    redirect_to projects_path
  end
  private
  def project_params
     params.require(:project).permit(:title,:description)
  end
  def story_params
    params.require(:story).permit(:title,:description)
  end
  def user_params
    params.require(:user).permit(:email)
  end

  def logged_in_user
    unless logged_in?
      flash[:danger]="Pleasee log in."
      redirect_to login_path
    end
  end

  def correct_user
    @user=User.find(params[:id])
    redirect_to(current_user) unless current_user?(@user)
  end
  
  def aviable_developers
    @developers=Array.new
    User.all.each do |user|
      #if( !user.admin && !user.project_id)
      @developers << user unless ( user.admin || user.project_id )
    end
    return @developers
  end
  
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/add_developer.html.erb
<%= link_to 'Back', @project%>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

    <p><b>old value</b></p>
    <table border="2">
      <tr>
        <td align="center" width="100">Title:</td>
        <td align="center" width="100">Description:</td>
      </tr>
      <tr>
        <td align="center"><%= @project.title %></td>
        <td align="center"><%= @project.description %></td>
      </tr>
    </table>
    <p>---------------------------</p>

<strong>Fill new value here:</strong>
<%= form_for @project, url: project_path(@project), method: :patch do |p| %>
    <table border="2">
      <tr>
        <td align="center" width="180"><%= p.label :title %></td>
        <td align="center" width="180"><%= p.label :description %></td>
      </tr>
      <tr>
        <td align="center"><%= p.text_field :title %></td>
        <td align="center"><%= p.text_field :description %></td>
      </tr>
    </table>
    <br>
     <p>
       <% if current_user.admin%>
       <%= p.label :developers %><br>
       <% if @chosen_dev %>
          <% @chosen_dev.each do |developer| %>
            <%= check_box_tag "developer_ids[]", developer.id, true%>
          <%= developer.name+" ("+developer.email+")"%>
          <br>
          <% end %>
        <% end %>
      
        <% if @developers %>
          <% @developers.each do |developer| %>
            <%= check_box_tag "developer_ids[]", developer.id%>
          <%= developer.name+" ("+developer.email+")" %>
          <br>
          <% end %>
        <% end %>
         <% end %>
    </p>
    <p>
      <%= p.submit 'update' %>
    </p>

<% end %>

<b><u><%= link_to 'Back', projects_path %></u></b>

app/views/projects/index.html.erb
<h1>Listing projects</h1>
<h2>ATTENTION: Only if you have the right to click a button, the button is able to be clicked!</h2>
<% if current_user.admin? %>
<p><b><u><%= link_to 'New Project', new_project_path %></u></b></p>
<% end %>

<table align="left" border="2">
  <thead>
  <tr>
    <td align="center">Title</td>
    <th colspan="3"></th>
  </tr>
  </thead>
  <tbody>
    <% @projects.each do |p| %>
      <tr>
        <td width="150" align="center"><%= p.title %></td>
        <td width="100" align="center"><u><b><%= link_to 'Show', project_path(p)%></b></u></td>
        <td width="100" align="center">
            <% if current_user.project_id == p.id || current_user.admin %>
              <u><b><%= link_to 'Edit  ', edit_project_path(p)%></b></u>
             <% else %>
                Edit
            <% end %>
        </td>
        <td width="100" align="center">
          <% if current_user.admin? || current_user.project_id == p.id%>
              <u><b><%= link_to 'Destroy  ', project_path(p), method: :delete,data:{confirm: 'Are you sure?'}%></b></u>
          <% else %>
             Destroy
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<br><br><br><br><br><br><br><br><br><br><br><br><br><br>
<br><br>

app/views/projects/new.html.erb
<h1>New Project</h1>
<%= form_for :project, url: projects_path do |p| %>
    <% if @project.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@project.errors.count, "error") %> prohibited
            this project from being saved:
          </h2>
          <ul>
            <% @project.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <p>
      <%= p.label :title %><br>
      <%= p.text_field :title %>
    </p>

    <p>
      <%= p.label :description %><br>
      <%= p.text_area :description %>
    </p>
    
    <p>
       <%= p.label :Add_Drevelopers %><br>
       <% if @developers %>
          <% @developers.each do |developer| %>
            <%= check_box_tag "developer_ids[]", developer.id %>
          <%= developer.name+" ("+developer.email+")" %>
          <br>
          <% end %>
       <% end %>
      
    </p>

    <p>
      <%= p.submit %>
    </p>
<% end %>
<%=link_to 'back', projects_path %>

app/views/projects/search.html.erb
<br><br><br>
<strong>Search Result:</strong>
<br><br>
<table border="2">
  <tr>
    <td align="center" width="100">Title</td>
    <td align="center" width="100">Description</td>
    <td align="center" width="100">Point</td>
    <td align="center" width="100">Stage</td>
    <td align="center" width="100">Developer1</td>
    <td align="center" width="100">Developer2</td>
  </tr>
<% if @stories!=nil%>
    <% @stories.each do |s|%>
          <% if s.project_id == @project.id%>
          <tr>
            <td align="center">
              <%= s.title%>
            </td>
            <td align="center">
              <%= s.description%>
            </td>
            <td align="center">
              <%= s.point%>
            </td>
            <td align="center">
              <%= s.stage%>
            </td>
            <td align="center">
              <% if s.users[0] %>
                <%= s.users[0].name+" ("+s.users[0].email+")"%>
              <% end%>
            </td>
            <td align="center">
              <% if s.users[1] %>
                  <%= s.users[1].name+" ("+s.users[1].email+")"%>
              <% end%>
            </td>
          </tr>
          <% end %>
    <% end %>
<%end%>
</table>
<br><br>

<b><u><%=link_to 'Back', project_stories_path(@project)%></u></b>

app/views/projects/show.html.erb
<h1>Show Project</h1>
<h2>ATTENTION: Only if you have the right to click a button, the button is able to be clicked!</h2>
<p>
  <strong>Title:</strong>
  <%= @project.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<p>
<strong>storyboard:</strong>
  <table title="storyboard" border="2">
  <tr>
    <td width="100" align="center">Analysis</td>
    <td width="100" align="center">Ready For Dev</td>
    <td width="100" align="center">In Dev</td>
    <td width="100" align="center">Dev Complete</td>
    <td width="100" align="center">In Test</td>
  </tr>
  <tr>
    <td align="center"><%= @point1%></td>
    <td align="center"><%= @point2%></td>
    <td align="center"><%= @point3%></td>
    <td align="center"><%= @point4%></td>
    <td align="center"><%= @point5%></td>
  </tr>
  </table>
</p>

<p>
  <strong>Developer:</strong>
  <table border="2">
    <tr>
      <td width="100" align="center">Name</td>
      <td width="100" align="center">Email</td>
    </tr>
    <% @project.users.each do |u| %>
    <tr>
        <td align="center"><%= u.name %></td>
        <td align="center"><%= u.email %></td>
    </tr>
    <% end %>
  </table>
</p>

<% if current_user.project_id == @project.id || current_user.admin %>
    <b><u><%= link_to 'Edit Project ', edit_project_path(@project)%></u></b>
<% end %>
<br><br>
<strong>search for projects:</strong>
<%=form_for :story, url: search_path(@project) do |f|%>
    <table border="2">
      <tr>
        <td align="center"><%=f.label :title%></td>
        <td align="center"><%=f.label :description%></td>
        <td></td>
      </tr>
      <tr>
        <td><%=f.text_field :title%></td>
        <td><%=f.text_field :description%></td>
        <td><%=f.submit 'search'%></td>
      </tr>
    </table>
<%end%>

<br>
<b><u><%= link_to 'Show All Stories',project_stories_path(@project) %></u></b>
<br><br>
<b><u><%= link_to 'Back', projects_path%></u></b>