config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'

  get 'static_pages/help'

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'about' => 'static_pages#about'

  get 'help' => 'static_pages#help'
  get 'contact' => 'static_pages#contact'

  root                 'static_pages#home'

  get   'login' => 'sessions#new'
  post   'login' =>'sessions#create'
  delete  'logout' =>'sessions#destroy'

  get 'signup' => 'users#new'
  resources :users
  post 'projects/:id' =>'projects#add_developer'
  post 'projects/:project_id/stories/:id'=>'stories#replace_user'
  get 'projects/:project_id/stories/:id/signoff'=>'stories#signoff', as: :signoff
  post 'projects/:project_id/search'=>'projects#search', as: :search

  resources :projects do
    resources :stories
  end

end

app/models/story.rb
class Story < ActiveRecord::Base
  belongs_to :project
  has_many :users
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  def index
    @project = Project.find(params[:project_id])
    @stories = @project.stories.all
  end

  def replace_user
    @project = Project.find(params[:project_id])
    if params[:id]!=nil

      @temp_story=Story.find(params[:id])

      if @temp_story.users[0]!=current_user && @temp_story.users[1]!=current_user
        @selected_user = User.find(params[:user][:id])
        @selected_user.story_id = nil
        @selected_user.save
        current_user.story_id = @temp_story.id
        current_user.save
      end
        redirect_to project_stories_path(@project)
    end
  end

  def show
    @project = Project.find(params[:project_id])
    @story = Story.find(params[:id])
    if @story.users.count<2
      current_user.story_id = @story.id
      current_user.save

      redirect_to project_stories_path(@project)

    else
      render 'replace'
    end
  end

  def signoff
    @project = Project.find(params[:project_id])
    @story = Story.find(params[:id])
    current_user.story_id = nil
    current_user.save
    redirect_to project_stories_path(@project)
  end

  def edit
    @project = Project.find(params[:project_id])
    @story = Story.find(params[:id])
  end

  def update
    @project = Project.find(params[:project_id])
    @story = Story.find(params[:id])
    @story.update(story_params)
    redirect_to project_stories_path(@project,@story)
  end

  def create
    @project = Project.find(params[:project_id])
    @story = @project.stories.create(story_params)
    @story.createdby= current_user.id
    @story.save
    redirect_to project_stories_path(@project)
  end

  def destroy
    @project = Project.find(params[:project_id])
    @story = @project.stories.find(params[:id])
    @story.users.each do|u|
      u.story_id =nil
      u.save
    end
    @story.destroy
    redirect_to project_stories_path(@project)
  end
  private
    def story_params
      params.require(:story).permit(:title, :description, :point, :stage)
    end
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/stories/_form.html.erb
<%= form_for([@project, @project.stories.build]) do |p| %>
    <strong>create new story</strong>
    <table border="2">
      <tr>
        <td align="center"><%= p.label :title %></td>
        <td align="center"><%= p.label :description %></td>
        <td align="center"><%= p.label :point %></td>
        <td align="center"><%= p.label :stage %></td>
        <td align="center"></td>
      </tr>
      <tr>
        <td><%= p.text_field :title %></td>
        <td><%= p.text_field :description %></td>
        <td><%= p.text_field :point %></td>
        <td><%= p.select(:stage,[['Analysis', 'Analysis'],['Ready For Dev','Ready For Dev'], ['In Dev', 'In Dev'],['Dev Complete','Dev Complete'],['In Test','In Test'],['Complete','Complete']]) %></td>
        <td><%= p.submit %></td>
      </tr>
    </table>
<% end %>

app/views/stories/_story.html.erb
<p>
  <strong>Title:</strong>
  <%= story.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= story.description %>
</p>

<p>
  <strong>Point:</strong>
  <%= story.point %>
</p>

<p>
  <strong>Stage:</strong>
  <%= story.stage %>
</p>

<p>
  <strong>Developer:</strong>
      <%= story.users.each do |u| %>
        <p>Name:<%= u.name %></p>
        <p>Email:<%= u.email %></p>
      <% end %>
</p>
<p>
  <% if !current_user.admin? && @project.id == current_user.project_id &&current_user.story_id ==nil %>
  <%= link_to 'Sign Up' , @story %>
  <% end %>
  <% if !current_user.admin? && @project.id == current_user.project_id %>
  <%= link_to 'Destroy Story',[story.project,story],method: :delete, data:{confirm: 'are you sure?'}%>
  <% end%>
</p>
<p>---------------------------</p>

app/views/stories/edit.html.erb
<h1>Editing story</h1>
<p>
  <strong>Title:</strong>
  <%= @story.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @story.description %>
</p>

<p>
  <strong>Point:</strong>
  <%= @story.point %>
</p>

<p>
  <strong>Stage:</strong>
  <%= @story.stage %>
</p>
<%= form_for @story, url: project_story_path(@project,@story),  method: :patch do |p| %>

    <p>
      <%= p.label :title %><br>
      <%= p.text_field :title %>
    </p>

    <p>
      <%= p.label :description %><br>
      <%= p.text_area :description %>
    </p>
    <p>
      <%= p.label :point %><br>
      <%= p.text_field :point %>
    </p>
    <p>
      <%= p.label :stage %><br>
      <%= p.select(:stage,[['Analysis', 'Analysis'],['Ready For Dev','Ready For Dev'], ['In Dev', 'In Dev'],['Dev Complete','Dev Complete'],['In Test','In Test'],['Complete','Complete']]) %>
    </p>
    <p>
      <%= p.submit 'update'%>
    </p>

<% end %>

<%= link_to 'Back', project_stories_path(@project) %>

app/views/stories/index.html.erb
<h1>Listing stories</h1>
<h2>ATTENTION: Only if you have the right to click a button, the button is able to be clicked!</h2>
<strong>search for projects:</strong>
<%=form_for :story, url: search_path(@project) do |f|%>
    <table border="2">
      <tr>
        <td align="center"><%=f.label :title%></td>
        <td align="center"><%=f.label :description%></td>
        <td></td>
      </tr>
      <tr>
        <td><%=f.text_field :title%></td>
        <td><%=f.text_field :description%></td>
        <td><%=f.submit 'search'%></td>
      </tr>
    </table>
<%end%>
<br>

<strong>list stories:</strong>
<% if @stories.count > 0%>
<table border="2">
  <tr>
    <td align="center" width="100">Title</td>
    <td align="center" width="100">Description</td>
    <td align="center" width="100">Point</td>
    <td align="center" width="100">Stage</td>
    <td align="center" width="100">Developer1</td>
    <td align="center" width="100">Developer2</td>
    <td align="center" width="100"></td><td align="center" width="100"></td><td align="center" width="100"></td>
  </tr>
<% @stories.each do |story| %>
    <tr>
      <td align="center"><%= story.title %></td>
      <td align="center"><%= story.description %></td>
      <td align="center"><%= story.point %></td>
      <td align="center"><%= story.stage %></td>
      <td align="center">
        <% if story.users[0]&& current_user!= story.users[0] %>
            <%= story.users[0].name+" ("+ story.users[0].email+")" %>
        <% elsif current_user  == story.users[0] %>
            <b><%= link_to 'SignOff', signoff_path(@project,story) %></b>
        <% elsif current_user&&!current_user.admin? && @project.id == current_user.project_id &&current_user.story_id ==nil%>
            <b><%= link_to 'SignUp' ,project_story_path(@project, story)%></b>
        <% end %>
      </td>
      <td align="center">
        <% if story.users[1]&& current_user!= story.users[1]%>
            <%= story.users[1].name+" ("+ story.users[1].email+")" %>
        <% elsif current_user  == story.users[1] %>
            <b><%= link_to 'SignOff', signoff_path(@project,story) %></b>
        <% elsif current_user&&!current_user.admin? && @project.id == current_user.project_id &&current_user.story_id ==nil%>
            <b><%= link_to 'SignUp' ,project_story_path(@project, story)%></b>
        <% end %>
      </td>
      <td align="center">
        <% if (current_user && @project.id == current_user.project_id)|| current_user.admin %>
            <b><%= link_to 'Edit', edit_project_story_path(@project, story)%></b>
        <% else%>
            Edit
        <% end %>
      </td>
      <td align="center">
        <% if (current_user && @project.id == current_user.project_id) || current_user.admin %>
            <b><%= link_to 'Destroy',[story.project,story],method: :delete, data:{confirm: 'are you sure?'}%></b>
        <% else %>
            Destroy
        <% end%>
      </td>
      <td align="center">
        <% if current_user.project_id == @project.id && story.users.count==2 && current_user.story_id ==nil%>
            <b><%= link_to 'replace', project_story_path(@project, story)%></b>
        <% else %>
            replace
        <% end %>
      </td>
    </tr>
<% end %>
</table>
<% else %>
    There is no story in this project right now, please create one!
    <br>
<% end %>


<br>
<% if (current_user && @project.id == current_user.project_id)|| current_user.admin %>
<%= render 'form' %>
<% end %>
<br>
<b><u><%= link_to 'Back', @project%></u></b>

app/views/stories/replace.html.erb
<h1>replace</h1>
<strong>Story Information:</strong>
<br><br>
<table border="2">
  <tr>
    <td align="center" width="150">Title:</td>
    <td align="center" width="150">Description</td>
    <td align="center" width="150">Point</td>
    <td align="center" width="150">Stage</td>
  </tr>
  <tr>
    <td align="center"><%= @story.title%></td>
    <td align="center"><%= @story.description%></td>
    <td align="center"><%= @story.point%></td>
    <td align="center"><%= @story.stage%></td>
  </tr>
</table>
<br>
<p>----------------------------------------------------------------------------</p>
<strong>developers:</strong>
<br><br>
<%= form_for :user, url:project_story_path(@project,@story) do |f| %>
    <table border="1">
      <tr>
        <td width="100" align="center">
          <%=f.label :name%>
        </td>
        <td width="100" align="center">
          <%=f.label :email%>
        </td>
        <td></td>
      </tr>
      <tr>
        <td width="100" align="center">
          <%= @story.users[0].name %>
        </td>
        <td width="100" align="center">
          <%= @story.users[0].email %>
        </td>
        <td>
          <%=f.hidden_field :id,:value =>@story.users[0].id%>
          <%= f.submit 'replace'%>
        </td>
      </tr>
    </table>
<% end %>
<%= form_for :user, url:project_story_path(@project,@story) do |f| %>
    <table border="1">
      <tr>
        <td width="100" align="center">
          <%=f.label :name%>
        </td>
        <td width="100" align="center">
          <%=f.label :email%>
        </td>
        <td></td>
      </tr>
      <tr>
        <td width="100" align="center">
          <%= @story.users[1].name %>
        </td>
        <td width="100" align="center">
          <%= @story.users[1].email %>
        </td>
        <td>
          <%=f.hidden_field :id,:value =>@story.users[1].id%>
          <%= f.submit 'replace'%>
        </td>
      </tr>
    </table>
<% end %>

app/views/stories/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @story.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @story.description %>
</p>

<p>
  <strong>Point:</strong>
  <%= @story.point %>
</p>

<p>
  <strong>Stage:</strong>
  <%= @story.stage %>
</p>
<p>
  <strong>Developer:</strong>
  <% @story.users.each do |u| %>
    <p>Name:<%= u.name %></p>
    <p>Email:<%= u.email %></p>
<% end %>
</p>
<p>
  <%= link_to 'Back', project_stories_path(@project)%>
</p>