config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'

  get 'static_pages/help'

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'about' => 'static_pages#about'

  get 'help' => 'static_pages#help'
  get 'contact' => 'static_pages#contact'

  root                 'static_pages#home'

  get   'login' => 'sessions#new'
  post   'login' =>'sessions#create'
  delete  'logout' =>'sessions#destroy'

  get 'signup' => 'users#new'
  resources :users
  post 'projects/:id' =>'projects#add_developer'
  post 'projects/:project_id/stories/:id'=>'stories#replace_user'
  get 'projects/:project_id/stories/:id/signoff'=>'stories#signoff', as: :signoff
  post 'projects/:project_id/search'=>'projects#search', as: :search

  resources :projects do
    resources :stories
  end

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
   This is the CSC 517 project 1
  </small>
  <nav>
    <ul>
       <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <% if logged_in? %>
      <%= link_to current_user.name, current_user, id: "logo" %>
     <% end %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
       
        <% if logged_in? %>
          <li><%= link_to "Projects", projects_path %></li>
          <li><%= link_to "Users", users_path %></li>
          <li><%= link_to "Profile", current_user %></li>
          <li><%= link_to "Settings", edit_user_path(current_user) %></li>
          <li> <%= link_to "Log out", logout_path, method: "delete" %></li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
     <div class="container">
    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      </div>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer'%>
    </div>
  </body>
</html>